language: bash
services: docker

env:
  - NODE_VERSION="12" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.5.2" CGAL_VERSION="5.2.1"
  - NODE_VERSION="14" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.5.2" CGAL_VERSION="5.2.1"
  - NODE_VERSION="15" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.5.2" CGAL_VERSION="5.2.1"

script: bash ./scripts/build.sh

deploy:
  provider: script
  script: bash ./scripts/push.sh
  on:
    branch: master
