language: bash
services: docker

env:
  - NODE_VERSION="10" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.4.0" CGAL_VERSION="5.0.2"
  - NODE_VERSION="11" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.4.0" CGAL_VERSION="5.0.2"
  - NODE_VERSION="12" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.4.0" CGAL_VERSION="5.0.2"
  - NODE_VERSION="13" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.4.0" CGAL_VERSION="5.0.2"
  - NODE_VERSION="14" AMAZONLINUX_VERSION="2" OCCT_VERSION="7.4.0" CGAL_VERSION="5.0.2"

script: bash ./scripts/build.sh

deploy:
  provider: script
  script: bash ./scripts/push.sh
  on:
    branch: master
